mysql.host: 127.0.0.1
mysql.port: 3306
mysql.database: test
mysql.username: plugin_user
mysql.password: password

messages:
  read: "§cBalance: §e{balance}"
  add: "§cYou added §e{amount} §cto §e{player}'s §cbalance"
  remove: "§cYou removed §e{amount} §cfrom §e{player}'s §cbalance"
  error: "§cAn error occurred while executing the command"